services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mirzabot_app
    restart: always
    working_dir: /var/www/html
    environment:
      - REQUEST_TIMEOUT=${REQUEST_TIMEOUT}
      - DB_HOST=${DB_HOST}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - API_KEY=${BOT_TOKEN}
      - ADMIN_ID=${ADMIN_ID}
      - BOT_USERNAME=${BOT_USERNAME}
      - DOMAIN_HOST=${DOMAIN}
      - BOT_VERSION=${BOT_VERSION:-latest}
    volumes:
      - ./scripts/entrypoint.sh:/usr/local/bin/entrypoint.sh
      - mirzabot_code:/var/www/html/mirzaprobotconfig
    entrypoint: ["/usr/local/bin/entrypoint.sh"]
    depends_on:
      - db
    networks:
      - mirzanet

  web:
    image: nginx:alpine
    container_name: mirzabot_web
    restart: always
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - mirzabot_code:/var/www/html/mirzaprobotconfig
      - ./configs/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./ssl:/etc/nginx/ssl:ro
    depends_on:
      - app
    networks:
      - mirzanet

  db:
    image: mysql:8.0
    container_name: mirzabot_db
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASS}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASS}
    volumes:
      - mirzadb_data:/var/lib/mysql
    networks:
      - mirzanet

  pma:
    image: phpmyadmin/phpmyadmin
    container_name: mirzabot_pma
    restart: always
    environment:
      PMA_HOST: db
      PMA_USER: ${DB_USER}
      PMA_PASSWORD: ${DB_PASS}
      # This helps phpmyadmin know it's behind a reverse proxy
      PMA_ABSOLUTE_URI: https://nightmare.qzz.io/phpmyadmin/
    networks:
      - mirzanet

networks:
  mirzanet:
    driver: bridge

volumes:
  mirzadb_data:
  mirzabot_code:

